selenium tests update

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,24 +1,61 @@
-# name: CD Docker Build
+name: CD Docker Build
 
-# on:
-#   push:
-#     branches:
-#       - main
-#       - tester
-# jobs:
-#   build:
-#     runs-on: ubuntu-latest
+on:
+  push:
+    branches:
+      - Hotfix
 
-#     steps:
-#       - name: Checkout repository
-#         uses: actions/checkout@v4
+jobs:
+  build-and-deploy:
+    runs-on: ubuntu-latest
 
-#       - name: Set up JDK 21
-#         uses: actions/setup-java@v4
-#         with:
-#           java-version: '21'
-#           distribution: 'temurin'
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-#       - name: Run tests
-#         run: mvn test -Dtest="com.tfg.futstats.selenium.**"
-#         working-directory: ./Backend
+      - name: Set up Java 21
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+
+      - name: Install Docker Compose
+        run: |
+            sudo apt-get update
+            sudo apt-get install -y docker-compose
+      - name: Levantar contenedores en segundo plano
+        run: docker-compose up -d --build
+        working-directory: ./Docker
+
+      - name: Wait for MySQL in Docker
+        run: |
+          echo "Waiting for MySQL to be ready..."
+          retries=12
+          # "db" es el servicio definido en docker-compose.yml
+          until docker-compose exec -T db mysql -u root -p"17042002" -e "SELECT 1"; do
+            if [ $retries -le 0 ]; then
+              echo "MySQL not ready after multiple attempts, failing..."
+              exit 1
+            fi
+            echo "MySQL not ready, waiting..."
+            retries=$((retries-1))
+            sleep 5
+          done
+          echo "MySQL is ready!"
+        working-directory: ./Docker
+
+      - name: Set up Node.js 18.119
+        uses: actions/setup-node@v2
+        with:
+          node-version: '18.19'
+
+      - name: Install Angular CLI Globally
+        run: npm install -g @angular/cli
+
+      - name: Install Angular Dependencies
+        run: npm install
+        working-directory: ./Frontend
+
+        - name: Run Spring Boot tests Controllers
+        run:  mvn test -Dtest="com.tfg.futstats.selenium.**"
+        working-directory: ./Backend
