Update docker-compose-local.yml

diff --git a/.github/workflows/docker-compose-local.yml b/.github/workflows/docker-compose-local.yml
--- a/.github/workflows/docker-compose-local.yml
+++ b/.github/workflows/docker-compose-local.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - main  # Cambia 'main' por la rama que quieras monitorizar
+      - test
 
 jobs:
   build-and-deploy:
@@ -11,7 +12,7 @@ jobs:
 
     services:
       mysql:
-        image: mysql:8.0
+        image: mysql:8.0.22
         options: >-
           --env MYSQL_ROOT_PASSWORD=17042002
           --env MYSQL_DATABASE=api_rest
@@ -29,21 +30,20 @@ jobs:
           java-version: '21'
           distribution: 'temurin'
 
-    # Esperar a que la base de datos esté completamente lista antes de continuar
     - name: Wait for MySQL to be ready
       run: |
-        echo "Waiting for MySQL to be ready..."
-        retries=12  # Intentos antes de fallar
-        until mysql -h"localhost" -u"root" -p"17042002" -e "SELECT 1"; do
-          if [ $retries -le 0 ]; then
-            echo "MySQL not ready after multiple attempts, failing..."
-            exit 1
-          fi
-          echo "MySQL not ready, waiting..."
-          retries=$((retries-1))
-          sleep 5
-        done
-        echo "MySQL is ready!"
+          echo "Waiting for MySQL to be ready..."
+          retries=12
+          until mysql -h "mysql" -u "root" -p "17042002" -e "SELECT 1"; do
+            if [ $retries -le 0 ]; then
+              echo "MySQL not ready after multiple attempts, failing..."
+              exit 1
+            fi
+            echo "MySQL not ready, waiting..."
+            retries=$((retries-1))
+            sleep 5
+          done
+          echo "MySQL is ready!"
 
     - name: Run Spring Boot tests
       run: mvn test
