Update docker-compose-local.yml

diff --git a/.github/workflows/docker-compose-local.yml b/.github/workflows/docker-compose-local.yml
--- a/.github/workflows/docker-compose-local.yml
+++ b/.github/workflows/docker-compose-local.yml
@@ -4,7 +4,6 @@ on:
   push:
     branches:
       - main  # Cambia 'main' por la rama que quieras monitorizar
-      - tester
 
 jobs:
   build-and-deploy:
@@ -12,29 +11,39 @@ jobs:
 
     services:
       mysql:
-        image: mysql:8.0.22 
+        image: mysql:8.0
         options: >-
           --env MYSQL_ROOT_PASSWORD=17042002
           --env MYSQL_DATABASE=api_rest
           --env MYSQL_USER=root
           --env MYSQL_PASSWORD=17042002
-          --publish 3306:3306  
+          --publish 3306:3306
 
     steps:
     - name: Checkout repository
       uses: actions/checkout@v3
 
-    - name: Wait for MySQL to be ready
-      run: |
-            while ! mysqladmin ping -h"localhost" --silent; do
-            echo "Waiting for MySQL to be ready..."
-            sleep 5
-            done
-
     - name: Set up Java 21
       uses: actions/setup-java@v2
       with:
-        java-version: '21'
+          java-version: '21'
+          distribution: 'temurin'
+
+    # Esperar a que la base de datos esté completamente lista antes de continuar
+    - name: Wait for MySQL to be ready
+      run: |
+        echo "Waiting for MySQL to be ready..."
+        retries=12  # Intentos antes de fallar
+        until mysql -h"localhost" -u"root" -p"17042002" -e "SELECT 1"; do
+          if [ $retries -le 0 ]; then
+            echo "MySQL not ready after multiple attempts, failing..."
+            exit 1
+          fi
+          echo "MySQL not ready, waiting..."
+          retries=$((retries-1))
+          sleep 5
+        done
+        echo "MySQL is ready!"
 
     - name: Run Spring Boot tests
       run: mvn test
@@ -51,7 +60,7 @@ jobs:
     - name: Run Angular unit tests
       run: npm test -- --watch=false --browsers=ChromeHeadless
       working-directory: ./Frontend
-    
+
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
