Update docker-compose-local.yml

diff --git a/.github/workflows/docker-compose-local.yml b/.github/workflows/docker-compose-local.yml
--- a/.github/workflows/docker-compose-local.yml
+++ b/.github/workflows/docker-compose-local.yml
@@ -9,6 +9,16 @@ jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
 
+    services:
+      mysql:
+        image: mysql:8.0
+        options: >-
+          --env MYSQL_ROOT_PASSWORD=17042002
+          --env MYSQL_DATABASE=api_rest
+          --env MYSQL_USER=root
+          --env MYSQL_PASSWORD=17042002
+          --publish 3306:3306
+
     steps:
     - name: Checkout repository
       uses: actions/checkout@v3
@@ -18,6 +28,22 @@ jobs:
       with:
           java-version: '21'
           distribution: 'temurin'
+
+    # Esperar a que la base de datos esté completamente lista antes de continuar
+    - name: Wait for MySQL to be ready
+      run: |
+        echo "Waiting for MySQL to be ready..."
+        retries=12  # Intentos antes de fallar
+        until mysql -h"localhost" -u"root" -p"17042002" -e "SELECT 1"; do
+          if [ $retries -le 0 ]; then
+            echo "MySQL not ready after multiple attempts, failing..."
+            exit 1
+          fi
+          echo "MySQL not ready, waiting..."
+          retries=$((retries-1))
+          sleep 5
+        done
+        echo "MySQL is ready!"
 
     - name: Run Spring Boot tests
       run: mvn test
@@ -34,7 +60,7 @@ jobs:
     - name: Run Angular unit tests
       run: npm test -- --watch=false --browsers=ChromeHeadless
       working-directory: ./Frontend
-    
+
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
